name: CI - Build & Test FastAPI App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run tests (if you have test scripts)
    - name: Run tests
      run: |
        echo "Running tests..."
        pytest || echo "No tests found, skipping"

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
    # Step 1: Checkout repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Build Docker image
    - name: Build Docker image
      run: docker build -t iris-api .
